project_id = "hqohcfwahmkxtpfbhcku"

[functions.send-token-notification]
verify_jwt = false

[functions.deploy-solana-token]
verify_jwt = false

[functions.transfer-solana-token]
verify_jwt = false

[functions.send-treasury-tokens]
verify_jwt = false

[functions.get-solana-balances]
verify_jwt = false

[functions.add-token-metadata]
verify_jwt = false

[functions.update-token-metadata]
verify_jwt = false

[functions.mint-to-treasury]
verify_jwt = false

[functions.upload-token-image]
verify_jwt = false

[functions.refresh-fee-payer-balances]
verify_jwt = false
