project_id = "hqohcfwahmkxtpfbhcku"

[functions.send-token-notification]
verify_jwt = false

[functions.deploy-solana-token]
verify_jwt = false

[functions.transfer-solana-token]
verify_jwt = false

[functions.send-treasury-tokens]
verify_jwt = false

[functions.get-solana-balances]
verify_jwt = false

[functions.add-token-metadata]
verify_jwt = false

[functions.update-token-metadata]
verify_jwt = false

[functions.mint-to-treasury]
verify_jwt = false

[functions.upload-token-image]
verify_jwt = false

[functions.refresh-fee-payer-balances]
verify_jwt = false

[functions.send-submission-notification]
verify_jwt = false

[functions.scan-arbitrage]
verify_jwt = false

[functions.execute-arbitrage]
verify_jwt = false

[functions.top-up-fee-payers]
verify_jwt = false

[functions.generate-fee-payer]
verify_jwt = false

[functions.get-fee-payer-keypair]
verify_jwt = false

[functions.scan-evm-arbitrage]
verify_jwt = false

[functions.public-reserve-data]
verify_jwt = false

[functions.verify-reserve-hash]
verify_jwt = false

[functions.execute-evm-arbitrage]
verify_jwt = false

[functions.get-evm-ops-wallet-info]
verify_jwt = false

[functions.refresh-evm-fee-payer-balances]
verify_jwt = false
