project_id = "hqohcfwahmkxtpfbhcku"

[functions.send-token-notification]
verify_jwt = false

[functions.deploy-solana-token]
verify_jwt = false

[functions.transfer-solana-token]
verify_jwt = false

[functions.send-treasury-tokens]
verify_jwt = false
